### ISSUE TITLE
There should be a warning of erasure before retrieving the code

### ISSUE THREAD

**Issue by Haarolean** [offici5l/MiUnlockTool#41]
So I've waited for 300 hours to unlock the bootloader, today did run the app, got the following warning:

```
user data will be cleared when the device is unlocked.

Press Enter to unlock bootloader
```

So I had to cancel (via ctrl+c) to back my data up, and after that on the next app run got the following:

```
code 20030

Sorry, couldn't unlock more devices by this account this month.
```

Guess there should be a warning for that.

**Comment by offici5l** [comment]
to find out the reason, check : https://github.com/offici5l/MiUnlockTool/issues/22

(i've now added a new step before sending the request to ask the user to continue or exit. https://github.com/offici5l/MiUnlockTool/blob/main/MiUnlockTool.py#L331-L334)
