### ISSUE TITLE
What to do to unlock bootloader with termux method ?

### ISSUE THREAD

**Issue by NabuchodonosorII** [offici5l/MiUnlockTool#43]
Did installed termux and his API ran the 2 command lines, but what after that ? The command miunlock cannot be find.
![photo_2024-07-01_11-41-45](https://github.com/offici5l/MiUnlockTool/assets/169909125/dbfafe2e-1dcf-4ec8-b7ea-94e0d2eea7c0)

**Comment by offici5l** [comment]
Some packages were not successfully installed possibly due to connection failure. Just rerun the installation command
