### ISSUE TITLE
Its stuck at unlocking process

### ISSUE THREAD

**Issue by cankurttekin** [offici5l/MiUnlockTool#46]
**Describe the bug**
After confirming with Enter the Press Enter to Unlock it stays at that screen forever. This is my second time trying, i had to to get new token.

**Screenshots**
![image](https://github.com/user-attachments/assets/a72890aa-3f99-4907-ba39-49de58eccc08)

**Comment by offici5l** [comment]
I have no idea !
Try reinstalling the MiUnlockTool again or changing the cable.

**Comment by auladlha-arch** [comment]
it goes the same for me, i havee changed the cable, reinstall MiUnlokTool and still goes the same, even i have been waiting for hours

**Comment by cankurttekin** [comment]
hey, try usb 2 port this worked for me back than
