### ISSUE TITLE
Code 30002

### ISSUE THREAD

**Issue by privatedev11** [offici5l/MiUnlockTool#47]
**Describe the bug**
When I attempt to unlock my device (Redmi Note 12 5G) it gives me an error that says "Code 30002. Couldn't unlock. Please go to Mi Community to apply for authorization and try again.". My account has authorization.

**Screenshots**
![Screenshot_20240801_092410](https://github.com/user-attachments/assets/bc6827f8-4c7a-4a10-ae04-b1fc9c14725a)

**Comment by offici5l** [comment]
Try changing the region by command 

in windows linux macos :

```
python3 MiUnlockTool.py global
```

in termux :

```
miunlock global
```

(or india, russia, china, europe)

If you have the same problem, use
https://github.com/offici5l/MiBypassTool

**Comment by privatedev11** [comment]
Thank you for your help, but in the end, I had to use the official tool because of the wait


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
