### ISSUE TITLE
code 20031

### ISSUE THREAD

**Issue by sysco55** [offici5l/MiUnlockTool#55]
**Describe the bug**

Redmi 13: 

code 20031

Please add your account in Settings > Developer options > Mi Unlock status.

Mi unlock status : send to app.

**Comment by offici5l** [comment]
If you have already added the account in the developer options successfully and you are facing this problem try change the server region :

ex: 

if windows linux macos :
```
python3 MiUnlockTool.py global
```

if termux :
```
miunlock global
```

Available region :
global, india, russia, china, europe
